import { NextResponse } from 'next/server';
import { eq } from 'drizzle-orm';
import { z } from 'zod';
import { db } from '@/lib/db';
import { purchases, supplierPayments, suppliers } from '@/lib/schema';
const schema=z.object({supplierId:z.string().uuid(),date:z.string().date().refine(date=>date<=new Date().toISOString().slice(0,10),{message:'Purchase date cannot be in the future.'}),description:z.string().trim().max(500).optional(),total:z.coerce.number().min(.01),paid:z.coerce.number().min(0),method:z.enum(['Cash','Card','Bank Transfer']).optional(),notes:z.string().trim().max(1000).optional()}).refine(v=>v.paid<=v.total,{path:['paid'],message:'Paid amount cannot exceed purchase total.'});
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const [purchase]=await db.select({id:purchases.id,invoiceNumber:purchases.invoiceNumber,supplierId:purchases.supplierId,purchaseDate:purchases.purchaseDate,description:purchases.description,total:purchases.total,paid:purchases.paid,paymentMethod:purchases.paymentMethod,notes:purchases.notes,createdAt:purchases.createdAt,supplierName:suppliers.name,supplierMobile:suppliers.mobile,supplierAddress:suppliers.address}).from(purchases).innerJoin(suppliers,eq(purchases.supplierId,suppliers.id)).where(eq(purchases.id,id));return purchase?NextResponse.json(purchase):NextResponse.json({error:'Purchase not found.'},{status:404});}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message},{status:400});try{const {id}=await params;const payments=await db.select().from(supplierPayments).where(eq(supplierPayments.purchaseId,id));const paymentTotal=payments.reduce((sum,p)=>sum+Number(p.amount),0);if(parsed.data.paid<paymentTotal)return NextResponse.json({error:'Paid amount cannot be lower than recorded supplier payments.'},{status:400});const [purchase]=await db.update(purchases).set({supplierId:parsed.data.supplierId,purchaseDate:parsed.data.date,description:parsed.data.description||null,total:String(parsed.data.total),paid:String(parsed.data.paid),paymentMethod:parsed.data.method||null,notes:parsed.data.notes||null}).where(eq(purchases.id,id)).returning();return NextResponse.json(purchase);}catch{return NextResponse.json({error:'Unable to update purchase.'},{status:500})}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const payments=await db.select({id:supplierPayments.id}).from(supplierPayments).where(eq(supplierPayments.purchaseId,id));if(payments.length)return NextResponse.json({error:'Purchase with recorded payments cannot be deleted.'},{status:409});await db.delete(purchases).where(eq(purchases.id,id));return NextResponse.json({ok:true});}catch{return NextResponse.json({error:'Unable to delete purchase.'},{status:500})}}
