import { NextResponse } from 'next/server';
import { eq, sql } from 'drizzle-orm';
import { z } from 'zod';
import { db } from '@/lib/db';
import { purchases, supplierPayments, suppliers } from '@/lib/schema';

const schema = z.object({ purchaseId: z.union([z.string().uuid(), z.literal('opening')]), date: z.string().date().refine(date => date <= new Date().toISOString().slice(0, 10)), amount: z.coerce.number().finite().positive(), method: z.enum(['Cash', 'Card', 'Bank Transfer']), notes: z.string().trim().max(1000).optional(), idempotencyKey: z.string().uuid().optional() });
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: 'Enter a valid payment request.' }, { status: 400 });
  try { const { id } = await params; const result = await db.transaction(async tx => {
    await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${id + parsed.data.purchaseId}))`); const key = parsed.data.idempotencyKey || crypto.randomUUID();
    if (parsed.data.purchaseId === 'opening') { const [supplier] = await tx.select().from(suppliers).where(eq(suppliers.id, id)); if (!supplier) throw Error('Supplier was not found.'); const previous = await tx.select({ amount: supplierPayments.amount }).from(supplierPayments).where(sql`${supplierPayments.supplierId} = ${id} and ${supplierPayments.purchaseId} is null`); const remaining = Number(supplier.openingBalance) - previous.reduce((total, payment) => total + Number(payment.amount), 0); if (parsed.data.amount > remaining + .00001) throw Error(`Payment cannot exceed the opening balance of AED ${remaining.toFixed(2)}.`); await tx.insert(supplierPayments).values({ supplierId: id, purchaseId: null, paymentDate: parsed.data.date, amount: String(parsed.data.amount), method: parsed.data.method, notes: parsed.data.notes || null, idempotencyKey: key }); return { remaining: remaining - parsed.data.amount }; }
    const [bill] = await tx.select().from(purchases).where(eq(purchases.id, parsed.data.purchaseId)); if (!bill || bill.supplierId !== id) throw Error('Purchase bill was not found.'); const remaining = Number(bill.total) - Number(bill.paid); if (parsed.data.amount > remaining + .00001) throw Error(`Payment cannot exceed the outstanding balance of AED ${remaining.toFixed(2)}.`); await tx.insert(supplierPayments).values({ supplierId: id, purchaseId: bill.id, paymentDate: parsed.data.date, amount: String(parsed.data.amount), method: parsed.data.method, notes: parsed.data.notes || null, idempotencyKey: key }); await tx.update(purchases).set({ paid: String(Number(bill.paid) + parsed.data.amount) }).where(eq(purchases.id, bill.id)); return { remaining: remaining - parsed.data.amount };
  }); return NextResponse.json(result, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to record payment.' }, { status: 400 }); }
}
