'use client';

import { Document, Page, StyleSheet, Text, View, pdf } from '@react-pdf/renderer';

export type PdfData = { kind:string; title:string; party?:string; business?:string[]; summary:[string,string][]; headers:string[]; rows:string[][]; notes?:string; sales?:{date:string;status:string;method:string;contact:string;address:string}; details?:[string,string][] };
const s=StyleSheet.create({
  page:{paddingTop:34,paddingBottom:42,paddingHorizontal:34,fontFamily:'Helvetica',fontSize:8,color:'#1f2933'},
  header:{borderBottomWidth:2,borderBottomColor:'#1d6b4f',paddingBottom:13,marginBottom:14,flexDirection:'row',justifyContent:'space-between'},
  company:{maxWidth:310},companyName:{color:'#164e3b',fontSize:19,fontFamily:'Helvetica-Bold'},companyLine:{color:'#52616b',fontSize:7.5,marginTop:3},
  doc:{alignItems:'flex-end'},kind:{color:'#164e3b',fontFamily:'Helvetica-Bold',fontSize:15},number:{color:'#52616b',marginTop:4,fontSize:8},
  info:{flexDirection:'row',gap:12,marginBottom:13},box:{borderWidth:1,borderColor:'#d6dfda',padding:9,flex:1,minHeight:58},facts:{width:210},
  label:{color:'#62716a',fontSize:6.5,fontFamily:'Helvetica-Bold',marginBottom:5},party:{fontFamily:'Helvetica-Bold',fontSize:10},detail:{color:'#52616b',fontSize:7.5,marginTop:3},
  fact:{flexDirection:'row',justifyContent:'space-between',marginBottom:4},factLabel:{color:'#62716a'},factValue:{fontFamily:'Helvetica-Bold'},
  summary:{flexDirection:'row',borderWidth:1,borderColor:'#d6dfda',marginBottom:14},summaryCell:{padding:8,flex:1,borderRightWidth:1,borderRightColor:'#d6dfda'},summaryLast:{borderRightWidth:0,backgroundColor:'#eaf5ee'},summaryValue:{color:'#164e3b',fontFamily:'Helvetica-Bold',fontSize:9},
  section:{color:'#164e3b',fontFamily:'Helvetica-Bold',fontSize:8.5,marginBottom:6,textTransform:'uppercase'},table:{borderWidth:1,borderColor:'#cbd7d0'},row:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:'#dce5e0',minHeight:23,alignItems:'stretch'},headRow:{backgroundColor:'#1d6b4f',minHeight:24},cell:{padding:5,flex:1,lineHeight:1.3},head:{color:'#fff',fontFamily:'Helvetica-Bold',fontSize:7},desc:{flex:2.25},index:{flex:.45,textAlign:'center'},qty:{flex:.8,textAlign:'right'},amount:{flex:1,textAlign:'right'},date:{flex:.85},type:{flex:.95},reference:{flex:1},statementDesc:{flex:1.75},status:{flex:1.1},
  bottom:{flexDirection:'row',justifyContent:'flex-end',marginTop:14},totals:{width:235,borderWidth:1,borderColor:'#cbd7d0'},totalRow:{flexDirection:'row',justifyContent:'space-between',padding:7,borderBottomWidth:1,borderBottomColor:'#dce5e0'},totalStrong:{backgroundColor:'#dcefe3',padding:9},totalLabel:{fontSize:8},totalValue:{fontFamily:'Helvetica-Bold',textAlign:'right'},notes:{marginTop:14,padding:8,borderWidth:1,borderColor:'#d6dfda',color:'#52616b',lineHeight:1.4},footer:{position:'absolute',bottom:18,left:34,right:34,borderTopWidth:1,borderTopColor:'#d6dfda',paddingTop:6,color:'#718078',fontSize:6.5,textAlign:'center'}
});
function Doc({data}:{data:PdfData}) {
 const invoice=data.kind==='Sales Invoice'||data.kind==='Purchase Bill'||data.kind==='Price List';
 const statement=data.kind==='Supplier Statement'||data.kind==='Customer Statement';
 const statementHasReference=data.headers.includes('Reference');
 const cell=(i:number)=>(data.kind==='Sales Invoice'||data.kind==='Price List')?[s.cell,i===0?s.index:i===1?s.desc:i===2?s.qty:s.amount]:data.kind==='Purchase Bill'?[s.cell,i===0?s.statementDesc:i>=1&&i<=3?s.amount:s.status]:[s.cell,i===0?s.date:i===1?s.type:statementHasReference?(i===2?s.reference:i===3?s.statementDesc:i>=4&&i<=6?s.amount:s.status):(i===2?s.statementDesc:i>=3&&i<=5?s.amount:s.status)];
 const emphasized=(label:string)=>['Grand Total','Current Outstanding','Outstanding Balance','Balance Amount'].includes(label);
 return <Document title={data.title} author="Veg Basket ERP"><Page size="A4" style={s.page} wrap>
  <View style={s.header} fixed={!statement}><View style={s.company}><Text style={s.companyName}>Veg Basket</Text>{(data.business || []).map((x,i)=><Text key={i} style={s.companyLine}>{x}</Text>)}</View><View style={s.doc}><Text style={s.kind}>{data.kind.toUpperCase()}</Text><Text style={s.number}>{data.title}</Text></View></View>
  <View style={s.info}><View style={s.box}><Text style={s.label}>{data.kind==='Customer Statement'||data.kind==='Sales Invoice'||data.kind==='Price List'?'BILL TO':'SUPPLIER'}</Text><Text style={s.party}>{data.party||'—'}</Text>{data.sales?.contact?<Text style={s.detail}>{data.sales.contact}</Text>:null}{data.sales?.address?<Text style={s.detail}>{data.sales.address}</Text>:null}</View>{invoice?<View style={[s.box,s.facts]}>{data.kind!=='Price List'&&<View style={s.fact}><Text style={s.factLabel}>Document No.</Text><Text style={s.factValue}>{data.title}</Text></View>}{data.sales&&<><View style={s.fact}><Text style={s.factLabel}>Date</Text><Text style={s.factValue}>{data.sales.date}</Text></View><View style={s.fact}><Text style={s.factLabel}>Payment Method</Text><Text style={s.factValue}>{data.sales.method}</Text></View><View style={s.fact}><Text style={s.factLabel}>Status</Text><Text style={s.factValue}>{data.sales.status}</Text></View></>}{data.details?.map(([label,value])=><View style={s.fact} key={label}><Text style={s.factLabel}>{label}</Text><Text style={s.factValue}>{value}</Text></View>)}</View>:null}</View>
  <View style={s.summary}>{data.summary.map(([l,v],i)=><View key={l} style={[s.summaryCell,i===data.summary.length-1?s.summaryLast:{}]}><Text style={s.label}>{l}</Text><Text style={s.summaryValue}>{v}</Text></View>)}</View>
  <Text style={s.section}>{invoice?'Details':'Transaction Details'}</Text><View style={s.table} wrap>{data.headers.length>0&&<View style={[s.row,s.headRow]} fixed>{data.headers.map((h,i)=><Text key={i} style={[cell(i),s.head]}>{h}</Text>)}</View>}{data.rows.map((r,n)=><View key={n} style={s.row} wrap={false}>{data.headers.map((_,i)=><Text key={i} style={cell(i)}>{r[i]||'—'}</Text>)}</View>)}</View>
  <View style={s.bottom}><View style={s.totals}>{data.summary.map(([l,v])=><View key={l} style={[s.totalRow,emphasized(l)?s.totalStrong:{}]}><Text style={s.totalLabel}>{l}</Text><Text style={s.totalValue}>{v}</Text></View>)}</View></View>
  {data.notes?<View style={s.notes}><Text style={s.label}>NOTES</Text><Text>{data.notes}</Text></View>:null}<Text style={s.footer} fixed>Veg Basket ERP · Computer generated document</Text>
 </Page></Document>;
}
function extract(el:HTMLElement):PdfData {
 const root=el.querySelector<HTMLElement>('.financial-document, .sale-invoice')||el;
 const kind=root.querySelector('.document-title b, .invoice-title span')?.textContent?.trim()||'Financial Document';
 const title=kind==='Sales Invoice'?root.querySelector('.invoice-facts p:first-child b')?.textContent?.trim()||kind:root.querySelector('.document-title strong')?.textContent?.trim()||kind;
 const table=root.querySelector('table');
 const summary=Array.from(root.querySelectorAll('.document-summary div, .invoice-summary span, .bill-summary span')).map(x=>{const b=x.querySelector('strong');return [b?x.textContent?.replace(b.textContent||'','').trim()||'Total':x.querySelector('small')?.textContent?.trim()||'Amount',b?.textContent?.trim()||x.querySelector('b')?.textContent?.trim()||'—'] as [string,string]});
 const sales=kind==='Sales Invoice'?{date:root.querySelector('.invoice-facts p:nth-child(2) b')?.textContent?.trim()||'—',status:root.querySelector('.invoice-status')?.textContent?.trim()||'—',method:root.querySelector('.payment-panel p b')?.textContent?.trim()||'—',contact:root.querySelector('.bill-to span')?.textContent?.replace(/\s+/g,' ').trim()||'',address:root.querySelector('.customer-address')?.textContent?.trim()||''}:undefined;
 return {kind,title,party:root.querySelector('.document-party b, .bill-to strong')?.textContent?.trim(),business:Array.from(root.querySelectorAll('.document-business small, .invoice-contact')).map(x=>x.textContent?.replace(/\s+/g,' ').trim()).filter(Boolean) as string[],summary:summary.length?summary:[['Total','—']],headers:table?Array.from(table.querySelectorAll('thead th')).map(x=>x.textContent?.trim()||''):[],rows:table?Array.from(table.querySelectorAll('tbody tr')).map(r=>Array.from(r.querySelectorAll('td')).map(x=>x.textContent?.replace(/\s+/g,' ').trim()||'—')):[],notes:root.querySelector('.invoice-notes p, .document-note')?.textContent?.trim(),sales};
}
export async function downloadPdfFromElement(element:HTMLElement,filename:string){const blob=await pdf(<Doc data={extract(element)}/>).toBlob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename.replace(/[^a-z0-9._-]+/gi,'-');a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function downloadPdf(data: PdfData, filename: string) { const blob = await pdf(<Doc data={data} />).toBlob(), url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = filename.replace(/[^a-z0-9._-]+/gi, '-'); a.style.display = 'none'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
