import { NextResponse } from 'next/server';
import { asc, eq } from 'drizzle-orm';
import { db } from '@/lib/db';
import { purchases, supplierPayments, suppliers } from '@/lib/schema';
import { z } from 'zod';
const updateSchema=z.object({name:z.string().trim().min(1).max(150),mobile:z.string().trim().min(5).max(30),address:z.string().trim().max(500).nullable().optional(),openingBalance:z.coerce.number().min(0)});
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const [supplier]=await db.select().from(suppliers).where(eq(suppliers.id,id));if(!supplier)return NextResponse.json({error:'Supplier not found.'},{status:404});const [bills,payments]=await Promise.all([db.select().from(purchases).where(eq(purchases.supplierId,id)).orderBy(asc(purchases.purchaseDate)),db.select({id:supplierPayments.id,supplierId:supplierPayments.supplierId,purchaseId:supplierPayments.purchaseId,paymentDate:supplierPayments.paymentDate,amount:supplierPayments.amount,method:supplierPayments.method,notes:supplierPayments.notes,createdAt:supplierPayments.createdAt}).from(supplierPayments).where(eq(supplierPayments.supplierId,id)).orderBy(asc(supplierPayments.paymentDate))]);const totalPurchases=bills.reduce((n,b)=>n+Number(b.total),0),totalPaid=bills.reduce((n,b)=>n+Number(b.paid),0);return NextResponse.json({supplier,bills,payments,summary:{openingBalance:Number(supplier.openingBalance),totalPurchases,totalPaid,payable:Number(supplier.openingBalance)+totalPurchases-totalPaid}});}catch{return NextResponse.json({error:'Unable to load supplier ledger.'},{status:503})}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const bills=await db.select({id:purchases.id}).from(purchases).where(eq(purchases.supplierId,id));if(bills.length)return NextResponse.json({error:'Suppliers with purchase history cannot be deleted.'},{status:409});await db.delete(suppliers).where(eq(suppliers.id,id));return NextResponse.json({ok:true});}catch{return NextResponse.json({error:'Unable to delete supplier.'},{status:500})}}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){const parsed=updateSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'Enter valid supplier details.'},{status:400});try{const {id}=await params;const [supplier]=await db.update(suppliers).set({name:parsed.data.name,mobile:parsed.data.mobile,address:parsed.data.address||null,openingBalance:String(parsed.data.openingBalance)}).where(eq(suppliers.id,id)).returning();return NextResponse.json(supplier);}catch{return NextResponse.json({error:'Unable to update supplier.'},{status:500})}}
