import { boolean, date, integer, numeric, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const users = pgTable('users', { id: uuid('id').defaultRandom().primaryKey(), email: text('email').notNull().unique(), passwordHash: text('password_hash').notNull(), name: text('name').notNull(), role: text('role').notNull().default('staff'), active: boolean('active').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow() });
export const suppliers = pgTable('suppliers', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), mobile: text('mobile').notNull(), address: text('address'), openingBalance: numeric('opening_balance', { precision: 14, scale: 2 }).notNull().default('0'), active: boolean('active').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow() });
export const purchases = pgTable('purchases', { id: uuid('id').defaultRandom().primaryKey(), invoiceNumber: text('invoice_number').notNull().unique(), supplierId: uuid('supplier_id').notNull().references(() => suppliers.id), purchaseDate: date('purchase_date').notNull(), description: text('description'), total: numeric('total', { precision: 14, scale: 2 }).notNull(), paid: numeric('paid', { precision: 14, scale: 2 }).notNull().default('0'), paymentMethod: text('payment_method'), notes: text('notes'), createdAt: timestamp('created_at').notNull().defaultNow() });
export const supplierPayments = pgTable('supplier_payments', { id: uuid('id').defaultRandom().primaryKey(), supplierId: uuid('supplier_id').notNull().references(() => suppliers.id), purchaseId: uuid('purchase_id').notNull().references(() => purchases.id), paymentDate: date('payment_date').notNull(), amount: numeric('amount', { precision: 14, scale: 2 }).notNull(), method: text('method').notNull(), notes: text('notes'), idempotencyKey: text('idempotency_key').notNull().unique(), createdAt: timestamp('created_at').notNull().defaultNow() });
export const sales = pgTable('sales', { id: uuid('id').defaultRandom().primaryKey(), invoiceNumber: text('invoice_number').notNull().unique(), customerName: text('customer_name').notNull(), saleDate: date('sale_date').notNull(), total: numeric('total', { precision: 14, scale: 2 }).notNull(), paid: numeric('paid', { precision: 14, scale: 2 }).notNull().default('0') });
export const expenses = pgTable('expenses', { id: uuid('id').defaultRandom().primaryKey(), category: text('category').notNull(), expenseDate: date('expense_date').notNull(), amount: numeric('amount', { precision: 14, scale: 2 }).notNull(), notes: text('notes') });
export const loans = pgTable('loans', { id: uuid('id').defaultRandom().primaryKey(), lender: text('lender').notNull(), outstanding: numeric('outstanding', { precision: 14, scale: 2 }).notNull(), originalAmount:numeric('original_amount',{precision:14,scale:2}), loanDate:date('loan_date'), minimumEmi:numeric('minimum_emi',{precision:14,scale:2}), description:text('description'), nextEmiDate: date('next_emi_date'), nextEmiAmount: numeric('next_emi_amount', { precision: 14, scale: 2 }) });
export const loanPayments=pgTable('loan_payments',{id:uuid('id').defaultRandom().primaryKey(),loanId:uuid('loan_id').notNull().references(()=>loans.id),paymentDate:date('payment_date').notNull(),amount:numeric('amount',{precision:14,scale:2}).notNull(),method:text('method').default('Cash'),notes:text('notes'),createdAt:timestamp('created_at').notNull().defaultNow()});
export const customers = pgTable('customers',{id:uuid('id').defaultRandom().primaryKey(),name:text('name').notNull(),mobile:text('mobile').notNull(),address:text('address'),openingBalance:numeric('opening_balance',{precision:14,scale:2}).notNull().default('0'),active:boolean('active').notNull().default(true),createdAt:timestamp('created_at').notNull().defaultNow()});
export const items = pgTable('items',{id:uuid('id').defaultRandom().primaryKey(),code:text('code').notNull().unique(),name:text('name').notNull(),description:text('description'),active:boolean('active').notNull().default(true),createdAt:timestamp('created_at').notNull().defaultNow()});
export const customerSales = pgTable('customer_sales',{id:uuid('id').defaultRandom().primaryKey(),invoiceNumber:text('invoice_number').notNull().unique(),customerId:uuid('customer_id').notNull().references(()=>customers.id),saleDate:date('sale_date').notNull(),subtotal:numeric('subtotal',{precision:14,scale:2}).notNull(),discount:numeric('discount',{precision:14,scale:2}).notNull().default('0'),total:numeric('total',{precision:14,scale:2}).notNull(),paid:numeric('paid',{precision:14,scale:2}).notNull().default('0'),paymentMethod:text('payment_method'),notes:text('notes'),createdAt:timestamp('created_at').notNull().defaultNow()});
export const saleItems = pgTable('sale_items',{id:uuid('id').defaultRandom().primaryKey(),saleId:uuid('sale_id').notNull().references(()=>customerSales.id),itemId:uuid('item_id').notNull().references(()=>items.id),quantity:numeric('quantity',{precision:14,scale:3}).notNull(),unit:text('unit'),unitPrice:numeric('unit_price',{precision:14,scale:2}).notNull(),lineTotal:numeric('line_total',{precision:14,scale:2}).notNull()});
export const customerPayments = pgTable('customer_payments',{id:uuid('id').defaultRandom().primaryKey(),customerId:uuid('customer_id').notNull().references(()=>customers.id),saleId:uuid('sale_id').notNull().references(()=>customerSales.id),paymentDate:date('payment_date').notNull(),amount:numeric('amount',{precision:14,scale:2}).notNull(),method:text('method').notNull(),notes:text('notes'),createdAt:timestamp('created_at').notNull().defaultNow()});
export const workers = pgTable('workers',{id:uuid('id').defaultRandom().primaryKey(),name:text('name').notNull(),mobile:text('mobile').notNull(),address:text('address'),joiningDate:date('joining_date'),notes:text('notes'),active:boolean('active').notNull().default(true),createdAt:timestamp('created_at').notNull().defaultNow()});
export const workerExpenses = pgTable('worker_expenses',{id:uuid('id').defaultRandom().primaryKey(),workerId:uuid('worker_id').notNull().references(()=>workers.id),expenseDate:date('expense_date').notNull(),purpose:text('purpose').notNull(),description:text('description'),amount:numeric('amount',{precision:14,scale:2}).notNull(),method:text('method').notNull(),expenseId:uuid('expense_id').references(()=>expenses.id).unique(),createdAt:timestamp('created_at').notNull().defaultNow()});
export const purseAdditions = pgTable('purse_additions',{id:uuid('id').defaultRandom().primaryKey(),amount:numeric('amount',{precision:14,scale:2}).notNull(),method:text('method').notNull(),date:date('date').notNull(),description:text('description'),createdAt:timestamp('created_at').notNull().defaultNow()});
